version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
      - mongodb
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: newMysql@123
      MYSQL_DATABASE: todo_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
